version: 1
name: auto-enum-plugin
debug: true
network:
  type: unix
  address: auto-enum-plugin.sock
settings:
  read:
    interval: 500s
    buffer: 150
  write:
    interval: 60s
    buffer: 150
    max: 50
  transaction:
    ttl: 600s

# the configuration option for setting auto-enumeration. the presence
# of this option will enable auto-enumeration processing on device
# registration. if this is set but no auto-enumeration handler is
# defined (rather, if the handler returns an unsupported error or the
# like), auto-enumeration will fail.
#
# the values under the auto_enumerate key are a list of maps - there
# is no scheme which these could conform to. whatever is required by
# the plugin should be stored here. for example, for IPMI, each entry
# in the list could be the configuration needed to connect to each
# BMC that will provide the device information.
auto_enumerate:
  - base: 10
  - base: 13